### PR TITLE
V0.9.3 release - ETW streaming and refactoring of aync usage

### PR DESCRIPTION
**Pull request by hpsin**
A big thank you to @CBaud and @dotMorten for adding ETW support and helping out with our use of async throughout the project.  

In addition, some minor changes that help with discovering whether a file in the File Explorer is a folder, and a helper method to determine if an app is sideloaded or not. Thank you to @Holo-Krzysztof for finding these shortcomings in the project. 

This includes one breaking change - ConnectAsync in the DevicePortal connection step now defaults to updateConnection:false, meaning that it will not attempt to move from a USB connection to a WiFi connection.  This likely will not impact the behavior of your application.

### CODE REVIEW

**Comment by dotMorten** [comment]
You don't want to include #218?

**Comment by WilliamsJason** [comment]
#218 needs more validation still. We can do two back-to-back updates of the NuGet package for that.

**Comment by hpsin** [comment]
We were planning to do two releases, one now and one after testing and integrating #218. We definitely want to get that in and released ASAP, and are at this moment testing it.  That said, looks like we'll roll it all into one release, since the team member with the binary signing privileges is out of the office.

**Comment by hpsin** [comment]
This is out of date - will wait on code signing

**Pull request merged**
