### PR TITLE
Http file streaming

### PR DESCRIPTION
**Pull request by dotMorten**
This is a first stab at using a custom http multipart content to avoid large memory consumption when installing large files.

Please DO NOT merge this yet. It needs some significant testing for the `InstallApplicationAsync` call, and I don't have all the scenarios currently available to test them all. I'm submitting this for issue #141 and asking for people to please give this a go and test it.

The UWP and .NET implementations are quite different and would need separate testing.

### CODE REVIEW

**Comment by WilliamsJason** [comment]
I'm starting to look at this finally. For a small appx with a single dependency on Xbox it succeeded but for a larger package it's failing with the following: Cannot access a disposed object.
Object name: 'SslStream'. This is on the line that copies the file to the outStream (await file.CopyToAsync(outStream); in HttpMultipartFileContent's SerializeToStreamAsync).

Still digging in, but I'll try to give you info as I get it in case you know what the issue is and how to address it.

**Comment by dotMorten** [comment]
There's a pretty good description of the problem in this PR: https://github.com/aspnet/KestrelHttpServer/pull/750.
Sounds like the connection was closed and we just need to try/catch it.
However that probably doesn't fix the issue (why was the connection closed?). I have noticed requests are often made twice, probably an unauthenticated one and then an authenticated one. Could be this is just getting rejected first time around?

**Comment by WilliamsJason** [comment]
Hmm. That's on the response though. This is failing while setting up the request still. I also noticed that sometimes it's an abort exception instead of the disposed exception.  I think something is closing the out stream that we are copying the file to after a pretty good number of bytes. I'll try a few more things.

**Comment by WilliamsJason** [comment]
I tried with a few different buffer sizes on the CopyToAsync of the large appx (up to a 1 GB buffer), but no luck. It super consistently fails at the same duration per buffer size though--slightly different duration for each buffer size but around 1.5 minutes for all of them. Could be a certain part of the appx file or count of bytes, could be something else.

**Comment by dotMorten** [comment]
I tried 4Gb last night in UWP, and it uploaded fine, and memory consumption stayed around 15mb (but failed install which could have been a different reason. Didn't get a chance to dive in why yet, since the file copy over 2GHz wifi took a looooong time)

**Comment by WilliamsJason** [comment]
I'm going to close this PR since I pulled it into my Fork and have a new PR up with the same changes. Thanks!

**Pull request closed without merging**
